spring.application.name=practice

#Enable console to check how thw data flow being processed inside the table.
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:file:/Z/Projects/practiceDB
spring.datasource.username=priyeDB
spring.datasource.password=priye123

spring.jpa.hibernate.ddl-auto=update