spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/test?useSSL=false
spring.datasource.username=root
spring.datasource.password=priye223@
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=9000

employee.service.base.url=http://localhost:8080/employee/

#logging level for whole application
logging.level.root=DEBUG

#logging level for specific packages
logging.level.com.prod_ready_feature.demo.controller=TRACE
logging.level.com.prod_ready_feature.demo.config=INFO
logging.pattern.console= %d [%level] %c{1.} [%t] --- %m%n

#To set the file name: it will create a log file with the name application.log in the root directory of the project
#logging.file.name = application.log
#To set the pattern for the log file
#logging.pattern.file = %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){green} [%level] %c{1.} [%t] %m%n

#To use logback-spring.xml for logging configuration, uncomment the following line
logging.config=classpath:logback-spring.xml

#Actuator endpoints configuration
management.endpoints.web.exposure.include=*
# To add any information to the /actuator/info endpoint
management.info.env.enabled=true
info.app.authors=Priye Arya
info.app.version=1.0.0
info.app.description=Demo Spring Boot Application with MySQL and Actuator

#open Api configuration
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
